### ISSUE TITLE
No suitable driver found for jdbc:sqlite

### ISSUE THREAD

**Issue by vemonet** [chrdebru/r2rml#5]
We are trying to convert a SQLite database (the chinook.db example) but r2rml is having trouble finding the driver 

```
2018-12-06 15:16:46 ERROR R2RMLProcessor:98 - Error connecting to database.
java.sql.SQLException: No suitable driver found for jdbc:sqlite:/data/chinook.db
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at r2rml.engine.R2RMLProcessor.createDatabaseConnection(R2RMLProcessor.java:90)
	at r2rml.engine.R2RMLProcessor.execute(R2RMLProcessor.java:39)
	at r2rml.Main.main(Main.java:59)
```

**Comment by vemonet** [comment]
If anyone needs it, we use
```xml
<dependency>
  <groupId>org.xerial</groupId>
  <artifactId>sqlite-jdbc</artifactId>
  <version>3.23.1</version>
</dependency>
```

And import in Main class:

```java
try { Class.forName("org.sqlite.JDBC").newInstance(); } catch(Exception e) {e.printStackTrace();};
```

**Comment by Kibubu** [comment]
I might have run into the same issue. This looks like a problem with the fatjar creation process. The `shade` plugin is not merging the jdbc service descriptions, instead only one driver description is kept in the final fatjar.

expected to find

```
> cat META-INF/services/java.sql.Driver
net.sourceforge.jtds.jdbc.Driver
com.microsoft.sqlserver.jdbc.SQLServerDriver
com.mysql.cj.jdbc.Driver
org.postgresql.Driver
oracle.jdbc.OracleDriver
org.h2.Driver
org.sqlite.JDBC
```

found
```
> cat META-INF/services/java.sql.Driver
net.sourceforge.jtds.jdbc.Driver
```
